# Generated by Django 6.0.6 on 2026-06-23 08:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('group_name', models.CharField(db_index=True, max_length=255)),
                ('group_code', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True)),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('billing_number', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='group_photos/')),
                ('is_active', models.BooleanField(default=False)),
                ('activation_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chairman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_groups', to=settings.AUTH_USER_MODEL)),
                ('secretary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretary_groups', to=settings.AUTH_USER_MODEL)),
                ('treasurer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treasurer_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_name', models.CharField(max_length=255)),
                ('record_type', models.CharField(choices=[('meeting_minutes', 'Meeting Minutes'), ('financial_report', 'Financial Report'), ('constitution', 'Constitution'), ('member_list', 'Member List'), ('other', 'Other')], max_length=50)),
                ('file', models.FileField(upload_to='group_records/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='groups.group')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_records',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('national_id', models.CharField(db_index=True, max_length=50)),
                ('national_id_photo', models.ImageField(blank=True, null=True, upload_to='national_ids/')),
                ('phone_number', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9]{10,15}$')])),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_members',
                'ordering': ['full_name'],
                'constraints': [models.UniqueConstraint(fields=('group', 'phone_number'), name='unique_group_phone'), models.UniqueConstraint(fields=('group', 'national_id'), name='unique_group_national_id')],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
