# Generated by Django 6.0.6 on 2026-06-24 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='billing_number',
        ),
        migrations.AddField(
            model_name='group',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='daily_transaction_limit',
            field=models.DecimalField(decimal_places=2, default=1000000, max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='ecoret_account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='ecoret_billing_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='max_loan_amount',
            field=models.DecimalField(decimal_places=2, default=500000, max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('mpamba', 'Mpamba'), ('airtel_money', 'Airtel Money'), ('tnm_mpamba', 'TNM Mpamba'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='virtual_account_holder',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='virtual_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
