# Generated by Django 6.0.6 on 2026-06-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_billing_number_group_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='billing_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
