# Generated by Django 6.0.6 on 2026-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_billing_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='cycle_duration_months',
            field=models.IntegerField(default=6, help_text='Duration of each group cycle in months'),
        ),
        migrations.AddField(
            model_name='group',
            name='cycle_end_date',
            field=models.DateField(blank=True, help_text='Date when the current group cycle ends', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='cycle_start_date',
            field=models.DateField(blank=True, help_text='Date when the current group cycle starts', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='default_interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Default interest rate (%) for all loans (Group and ECORET)', max_digits=5),
        ),
        migrations.AddField(
            model_name='group',
            name='is_cycle_active',
            field=models.BooleanField(default=False, help_text='Whether the current cycle is active'),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_day',
            field=models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], default='saturday', help_text='Which day of the week the group meets', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_frequency',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly')], default='weekly', help_text='How often the group meets', max_length=20),
        ),
        migrations.AddField(
            model_name='group',
            name='savings_max_contribution',
            field=models.DecimalField(decimal_places=2, default=10000.0, help_text='Maximum savings contribution per member per cycle', max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='savings_min_contribution',
            field=models.DecimalField(decimal_places=2, default=500.0, help_text='Minimum savings contribution per member per cycle', max_digits=10),
        ),
        migrations.AddField(
            model_name='group',
            name='social_max_contribution',
            field=models.DecimalField(decimal_places=2, default=5000.0, help_text='Maximum amount a member can contribute to social fund per cycle', max_digits=10),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='business_description',
            field=models.TextField(blank=True, help_text="Detailed description of the member's business", null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='business_type',
            field=models.CharField(blank=True, choices=[('farming', 'Farming'), ('trading', 'Trading/Shop'), ('retail', 'Retail Business'), ('salaried', 'Salaried Employment'), ('artisan', 'Artisan/Craft'), ('transport', 'Transport'), ('fishing', 'Fishing'), ('livestock', 'Livestock Rearing'), ('food_vendor', 'Food Vendor'), ('salon', 'Salon/Barber'), ('tailor', 'Tailoring/Sewing'), ('construction', 'Construction'), ('mining', 'Mining'), ('student', 'Student'), ('homemaker', 'Homemaker'), ('other', 'Other')], help_text='Type of business/occupation the member does', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='billing_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
    ]
