# Generated by Django 6.0.6 on 2026-07-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_cycle_duration_months_group_cycle_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmember',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='mobile_money_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='groupmember',
            name='mobile_money_provider',
            field=models.CharField(blank=True, choices=[('airtel', 'Airtel Money'), ('tnm', 'TNM Mpamba')], max_length=20, null=True),
        ),
    ]
