# Generated by Django 6.0.6 on 2026-06-23 08:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Saving',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saving_type', models.CharField(choices=[('voluntary', 'Voluntary'), ('compulsory', 'Compulsory')], default='voluntary', max_length=20)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal')], max_length=20)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings', to='groups.groupmember')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savings',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='SavingGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('target_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_goals', to='groups.group')),
            ],
            options={
                'db_table': 'saving_goals',
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='SavingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_deposits', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_deposit_count', models.IntegerField(default=0)),
                ('total_withdrawal_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saving_summaries', to='groups.group')),
            ],
            options={
                'db_table': 'saving_summaries',
                'ordering': ['-date'],
                'unique_together': {('group', 'date')},
            },
        ),
    ]
