# Generated by Django 6.0.6 on 2026-06-26 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loansettings',
            name='default_interest_rate',
        ),
        migrations.RemoveField(
            model_name='loansettings',
            name='max_duration_months',
        ),
        migrations.RemoveField(
            model_name='loansettings',
            name='max_loan_amount',
        ),
        migrations.RemoveField(
            model_name='loansettings',
            name='min_duration_months',
        ),
        migrations.AddField(
            model_name='loansettings',
            name='ecoret_loan_duration_months',
            field=models.IntegerField(default=12, help_text='Repayment duration in months for ECORET loans. Set by ECORET admin.'),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='ecoret_loan_interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='Interest rate (%) for ECORET loans. Set by ECORET admin.', max_digits=5),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='ecoret_loan_max_amount',
            field=models.DecimalField(decimal_places=2, default=1000000, help_text='Maximum ECORET loan amount. Set by ECORET admin.', max_digits=10),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='ecoret_loan_min_amount',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Minimum ECORET loan amount. Set by ECORET admin.', max_digits=10),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='grace_period_days',
            field=models.IntegerField(default=7, help_text='Days after due date before late fees apply.'),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='group_loan_duration_months',
            field=models.IntegerField(default=6, help_text='Repayment duration in months for group loans. Set by group chairman.'),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='group_loan_interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Interest rate (%) for group loans. Set by group chairman.', max_digits=5),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='group_loan_max_amount',
            field=models.DecimalField(decimal_places=2, default=500000, help_text='Maximum group loan amount. Set by group chairman.', max_digits=10),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='group_loan_min_amount',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Minimum group loan amount. Set by group chairman.', max_digits=10),
        ),
        migrations.AddField(
            model_name='loansettings',
            name='late_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Late fee as percentage of overdue amount.', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='min_guarantors',
            field=models.IntegerField(default=2, help_text='Minimum number of guarantors required for loans.'),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='requires_guarantor',
            field=models.BooleanField(default=True, help_text='Does this group require a guarantor for loans?'),
        ),
        migrations.CreateModel(
            name='ECORETSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ecoret_loan_interest_rate', models.DecimalField(decimal_places=2, default=5.0, help_text='Current ECORET loan interest rate (%)', max_digits=5)),
                ('ecoret_loan_duration_months', models.IntegerField(default=12, help_text='ECORET loan duration in months')),
                ('ecoret_loan_max_amount', models.DecimalField(decimal_places=2, default=1000000, help_text='Maximum ECORET loan amount', max_digits=10)),
                ('ecoret_loan_min_amount', models.DecimalField(decimal_places=2, default=10000, help_text='Minimum ECORET loan amount', max_digits=10)),
                ('service_fee_percentage', models.DecimalField(decimal_places=2, default=2.5, help_text='ECORET service fee (%) per transaction', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(help_text='Admin who last updated these settings', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ECORET Settings',
                'db_table': 'ecoret_settings',
            },
        ),
    ]
