# Generated by Django 6.0.6 on 2026-07-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_create_default_loan_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='loansettings',
            name='default_interest_rate',
            field=models.DecimalField(decimal_places=2, default=10.0, help_text='Default interest rate (%) for all loans', max_digits=5),
        ),
    ]
