# Generated by Django 6.0.6 on 2026-07-23 13:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_loansettings_default_interest_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ECORETBankAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Account nickname (e.g., 'ECORET Main')", max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('account_name', models.CharField(max_length=200)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_branch', models.CharField(blank=True, max_length=100)),
                ('bank_code', models.CharField(blank=True, help_text='Bank code for PayChangu', max_length=20)),
                ('account_type', models.CharField(choices=[('main', 'Main Account'), ('disbursement', 'Disbursement Account'), ('settlement', 'Settlement Account'), ('escrow', 'Escrow Account')], default='main', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('pending_verification', 'Pending Verification')], default='pending_verification', max_length=20)),
                ('currency', models.CharField(default='MWK', max_length=3)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('paychangu_account_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paychangu_verified', models.BooleanField(default=False)),
                ('paychangu_verification_date', models.DateTimeField(blank=True, null=True)),
                ('daily_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ecoret_bank_accounts',
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.AddField(
            model_name='loan',
            name='bank_transfer_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='cash_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='chairman_cash_receipt',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='chairman_disbursement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='chairman_disbursement_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('pending', 'Pending')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='chairman_disbursement_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='chairman_disbursement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='chairman_mobile_money_provider',
            field=models.CharField(blank=True, choices=[('airtel', 'Airtel Money'), ('tnm', 'TNM Mpamba')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='chairman_mobile_money_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='chairman_transfer_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursed_by_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_disbursed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ecoret_disbursed_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('pending', 'Pending - Awaiting Funds')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='loan',
            name='ecoret_pin_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='wait_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='wait_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='wait_reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wait_reported_loans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ecoretsettings',
            name='ecoret_loan_max_amount',
            field=models.DecimalField(decimal_places=2, default=1000000, help_text='Maximum ECORET loan amount', max_digits=15),
        ),
        migrations.AlterField(
            model_name='ecoretsettings',
            name='ecoret_loan_min_amount',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Minimum ECORET loan amount', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loan',
            name='total_payable',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='interest_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanrepayment',
            name='principal_paid',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='ecoret_loan_max_amount',
            field=models.DecimalField(decimal_places=2, default=1000000, help_text='Maximum ECORET loan amount. Set by ECORET admin.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='ecoret_loan_min_amount',
            field=models.DecimalField(decimal_places=2, default=10000, help_text='Minimum ECORET loan amount. Set by ECORET admin.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='group_loan_max_amount',
            field=models.DecimalField(decimal_places=2, default=500000, help_text='Maximum group loan amount. Set by group chairman.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='loansettings',
            name='group_loan_min_amount',
            field=models.DecimalField(decimal_places=2, default=1000, help_text='Minimum group loan amount. Set by group chairman.', max_digits=15),
        ),
        migrations.AddField(
            model_name='loan',
            name='disbursement_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_loans', to='loans.ecoretbankaccount'),
        ),
    ]
