# Generated by Django 6.0.6 on 2026-06-29 20:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('groups', '0003_group_billing_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meeting_date', models.DateField()),
                ('case_type', models.CharField(choices=[('late_coming', 'Late Coming'), ('absence', 'Absence'), ('early_departure', 'Early Departure'), ('no_excuse', 'No Excuse'), ('other', 'Other')], max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('penalty_due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('waived', 'Waived'), ('appealed', 'Appealed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_cases', to='groups.group')),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='attendance.meeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_cases', to='groups.groupmember')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_cases', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attendance_cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpamba', 'Mpamba'), ('airtel_money', 'Airtel Money'), ('bank_transfer', 'Bank Transfer'), ('deduction', 'Deducted from Savings')], max_length=20)),
                ('transaction_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('attendance_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='attendance.attendancecase')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_payments', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalty_payments', to='groups.groupmember')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'penalty_payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
