# Generated by Django 6.0.6 on 2026-06-23 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDOTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('otp_code', models.CharField(max_length=6)),
                ('purpose', models.CharField(choices=[('loan_approval', 'Loan Approval'), ('member_verification', 'Member Verification'), ('transaction', 'Transaction')], max_length=50)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('correlation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ussd_otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='USSDLoanRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending_otp', 'Pending OTP'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending_otp', max_length=20)),
                ('otp_session_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.groupmember')),
            ],
            options={
                'db_table': 'ussd_loan_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='USSDRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('service_code', models.CharField(max_length=20)),
                ('request_text', models.TextField()),
                ('response_text', models.TextField(blank=True)),
                ('group_code', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('timeout', 'Timeout')], default='started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.groupmember')),
            ],
            options={
                'db_table': 'ussd_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
