# Generated by Django 6.0.6 on 2026-06-24 09:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='USSDSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                ('group_code', models.CharField(blank=True, max_length=20, null=True)),
                ('group_id', models.UUIDField(blank=True, null=True)),
                ('member_id', models.UUIDField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=2)),
                ('current_menu', models.CharField(default='welcome', max_length=50)),
                ('loan_type', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('data', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ussd_sessions',
            },
        ),
        migrations.AlterModelOptions(
            name='ussdloanrequest',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ussdotp',
            options={},
        ),
        migrations.RemoveField(
            model_name='ussdrequest',
            name='status',
        ),
        migrations.AddField(
            model_name='ussdloanrequest',
            name='loan_type',
            field=models.CharField(default='group_loan', max_length=20),
        ),
        migrations.AlterField(
            model_name='ussdrequest',
            name='request_text',
            field=models.TextField(blank=True),
        ),
    ]
